[build]
command = "npm run build"
publish = ".next"

[build.environment]
NEXT_PUBLIC_SUPABASE_URL = "https://idpjifivdaqhsysvjmye.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_AnsRZjbCFV16hhH-gaff0A_shCdX8ju"
NODE_VERSION = "20"
