-- Faza 6: tokenuri de feed hash-uite, revocabile și jurnal complet de export.
-- Migrarea este aditivă și idempotentă. Tokenul în clar nu este stocat niciodată.

begin;

create table if not exists public.feed_tokens (
  id uuid primary key default gen_random_uuid(),
  agency_id uuid not null references public.agencies(id) on delete restrict,
  portal text not null check (portal in ('generic', 'storia')),
  label text not null,
  token_hash text not null unique check (length(token_hash) = 64),
  token_prefix text not null,
  config jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  generation integer not null default 1 check (generation > 0),
  created_by uuid references auth.users(id) on delete set null,
  revoked_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  rotated_at timestamptz,
  revoked_at timestamptz,
  expires_at timestamptz,
  last_used_at timestamptz,
  last_success_at timestamptz,
  last_error_at timestamptz
);

create index if not exists feed_tokens_agency_portal_idx
  on public.feed_tokens(agency_id, portal, created_at desc);
create index if not exists feed_tokens_active_hash_idx
  on public.feed_tokens(token_hash)
  where is_active = true;

create table if not exists public.feed_export_logs (
  id uuid primary key default gen_random_uuid(),
  token_id uuid references public.feed_tokens(id) on delete set null,
  agency_id uuid not null references public.agencies(id) on delete restrict,
  portal text not null,
  status text not null check (status in ('success', 'invalid_xml', 'error')),
  included_count integer not null default 0 check (included_count >= 0),
  excluded_count integer not null default 0 check (excluded_count >= 0),
  error_count integer not null default 0 check (error_count >= 0),
  exclusion_summary jsonb not null default '{}'::jsonb,
  error_code text,
  error_message text,
  duration_ms integer check (duration_ms is null or duration_ms >= 0),
  generated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists feed_export_logs_agency_generated_idx
  on public.feed_export_logs(agency_id, generated_at desc);
create index if not exists feed_export_logs_token_generated_idx
  on public.feed_export_logs(token_id, generated_at desc);

create table if not exists public.feed_export_log_items (
  id bigint generated by default as identity primary key,
  export_log_id uuid not null references public.feed_export_logs(id) on delete cascade,
  property_id uuid references public.properties(id) on delete set null,
  internal_code text,
  result text not null check (result in ('included', 'excluded', 'error')),
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists feed_export_log_items_log_idx
  on public.feed_export_log_items(export_log_id, result);

alter table public.feed_tokens enable row level security;
alter table public.feed_export_logs enable row level security;
alter table public.feed_export_log_items enable row level security;

-- Hash-urile și jurnalele sunt accesibile numai prin API-ul server-side după
-- verificarea permisiunii `feed`; nu sunt expuse direct sesiunilor din browser.
revoke all on public.feed_tokens from public, anon, authenticated;
revoke all on public.feed_export_logs from public, anon, authenticated;
revoke all on public.feed_export_log_items from public, anon, authenticated;
grant select, insert, update, delete on public.feed_tokens to service_role;
grant select, insert, update, delete on public.feed_export_logs to service_role;
grant select, insert, update, delete on public.feed_export_log_items to service_role;
grant usage, select on sequence public.feed_export_log_items_id_seq to service_role;

commit;
