'use client';

import { useAuth } from '@/lib/auth-context';

import { useEffect, useState, useRef } from 'react';
import { supabase } from '@/lib/supabase';
import { ProtectedLayout } from '@/components/ProtectedLayout';
import {
  Users, UserPlus, Search, Edit2, Trash2, X, ChevronDown, ChevronUp,
  Mail, Phone, Briefcase, Building2, Calendar, CheckCircle, XCircle,
  Shield, Activity, BarChart3, Home, Target, Clock, Eye, AlertTriangle,
  Check, Key, Upload,
} from 'lucide-react';
import { ROLES, ROLE_COLORS, MODULES, ACTIONS, DEFAULT_PERMISSIONS } from '@/lib/team-roles';

// ── Types ─────────────────────────────────────────────────────────────────────
interface Member {
  id: string;
  user_id: string;
  email: string;
  username?: string;
  contact_email?: string;
  full_name: string;
  first_name: string;
  last_name: string;
  phone: string;
  job_title: string;
  department: string;
  role: string;
  status: string;
  hired_at: string | null;
  avatar_url: string | null;
  notes: string;
  permissions: Record<string, Record<string, boolean>>;
  created_at: string;
  last_sign_in_at: string | null;
  stats: { properties_active: number; properties_sold: number; clients: number };
}

interface TeamStats {
  total_members: number;
  active_properties: number;
  sold_properties: number;
  total_clients: number;
  avg_properties_per_agent: number;
}

interface ActivityEvent {
  id: string;
  type: string;
  action: string;
  label: string;
  entity_id: string;
  entity_code: string;
  user_id: string;
  agent_name: string;
  created_at: string;
  meta: Record<string, string>;
}

const ic = 'w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-emerald-500 text-gray-900 text-sm';

// ── Helpers ───────────────────────────────────────────────────────────────────
function Avatar({ member, size = 10 }: { member: Pick<Member, 'avatar_url' | 'full_name'>; size?: number }) {
  const initials = (member.full_name || '?').split(' ').map(w => w[0]).join('').slice(0, 2).toUpperCase();
  // `size` follows the Tailwind scale (10 = 2.5rem = 40px). Use inline px so the
  // dimension is reliable — dynamic `w-${size}` classes are NOT generated by Tailwind.
  const px = size * 4;
  if (member.avatar_url) {
    return <img src={member.avatar_url} alt={member.full_name} className="rounded-full object-cover flex-shrink-0" style={{ width: px, height: px }} />;
  }
  const colors = ['bg-emerald-500', 'bg-blue-500', 'bg-purple-500', 'bg-orange-500', 'bg-pink-500', 'bg-teal-500'];
  const color = colors[initials.charCodeAt(0) % colors.length];
  return (
    <div className={`rounded-full ${color} flex items-center justify-center text-white font-bold flex-shrink-0`}
      style={{ width: px, height: px, fontSize: Math.max(13, Math.round(px * 0.38)) }}>
      {initials}
    </div>
  );
}

function RoleBadge({ role }: { role: string }) {
  return (
    <span className={`inline-flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full ${ROLE_COLORS[role] || 'bg-gray-100 text-gray-600'}`}>
      {ROLES[role] || role}
    </span>
  );
}

function StatusBadge({ status }: { status: string }) {
  return status === 'activ'
    ? <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700 bg-emerald-50 border border-emerald-200 px-2 py-0.5 rounded-full"><CheckCircle size={11} />Activ</span>
    : <span className="inline-flex items-center gap-1 text-xs font-medium text-red-600 bg-red-50 border border-red-200 px-2 py-0.5 rounded-full"><XCircle size={11} />Inactiv</span>;
}

function formatDate(d: string | null) {
  if (!d) return '—';
  return new Date(d).toLocaleDateString('ro-RO', { day: '2-digit', month: 'short', year: 'numeric' });
}

function formatRelative(d: string | null) {
  if (!d) return 'Niciodata';
  const diff = Date.now() - new Date(d).getTime();
  const mins = Math.floor(diff / 60000);
  if (mins < 60) return `${mins}m în urmă`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h în urmă`;
  const days = Math.floor(hrs / 24);
  if (days < 7) return `${days}z în urmă`;
  return formatDate(d);
}

// ── Add/Edit Agent Dialog ─────────────────────────────────────────────────────
function AgentDialog({
  member,
  members,
  onClose,
  onSuccess,
  token,
}: {
  member: Member | null;
  members: Member[];
  onClose: () => void;
  onSuccess: () => void;
  token: string;
}) {
  const isEdit = !!member;
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [openSec, setOpenSec] = useState<Record<string, boolean>>({ personal: true, role: true, perms: false });

  const [fd, setFd] = useState({
    first_name: member?.first_name || '',
    last_name: member?.last_name || '',
    username: member?.username || '',
    email: member?.contact_email || '',
    phone: member?.phone || '',
    password: '',
    job_title: member?.job_title || '',
    department: member?.department || '',
    role: member?.role || 'agent',
    status: member?.status || 'activ',
    hired_at: member?.hired_at || '',
    notes: member?.notes || '',
    avatar_url: member?.avatar_url || '',
  });
  const [perms, setPerms] = useState<Record<string, Record<string, boolean>>>(
    member?.permissions || DEFAULT_PERMISSIONS['agent']
  );

  const set = (k: string, v: string) => setFd(p => ({ ...p, [k]: v }));

  const onRoleChange = (role: string) => {
    set('role', role);
    setPerms(DEFAULT_PERMISSIONS[role] || DEFAULT_PERMISSIONS.agent);
  };

  const togglePerm = (mod: string, action: string) => {
    setPerms(p => ({ ...p, [mod]: { ...p[mod], [action]: !p[mod]?.[action] } }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const payload = { ...fd, permissions: perms };
      const url = isEdit ? `/api/team/members/${member.id}` : '/api/team/members';
      const method = isEdit ? 'PATCH' : 'POST';
      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify(payload),
      });
      const d = await res.json();
      if (!res.ok) throw new Error(d.error);
      onSuccess();
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Eroare');
    } finally {
      setLoading(false);
    }
  };

  const Sec = ({ id, title }: { id: string; title: string }) => (
    <button type="button" onClick={() => setOpenSec(p => ({ ...p, [id]: !p[id] }))}
      className="w-full flex justify-between items-center py-2.5 text-sm font-semibold text-gray-700 border-b border-gray-200 mb-3">
      <span>{title}</span>
      {openSec[id] ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
    </button>
  );

  return (
    <div className="mobile-dialog-backdrop fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="mobile-dialog-panel bg-white rounded-xl w-full max-w-2xl max-h-[92vh] flex flex-col shadow-xl">
        <div className="border-b px-6 py-4 flex justify-between items-center flex-shrink-0">
          <h2 className="text-xl font-bold" style={{ color: '#0E6B54' }}>
            {isEdit ? 'Editează Agent' : 'Adaugă Agent Nou'}
          </h2>
          <button onClick={onClose} className="p-1 hover:bg-gray-100 rounded"><X size={22} /></button>
        </div>

        <form onSubmit={handleSubmit} className="flex-1 overflow-y-auto px-6 py-4 space-y-4">
          {/* Date personale */}
          <div>
            <Sec id="personal" title="1. Date personale" />
            {openSec.personal && (
              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs font-medium text-gray-600 mb-1 block">Prenume</label>
                    <input className={ic} value={fd.first_name} onChange={e => set('first_name', e.target.value)} placeholder="Ion" />
                  </div>
                  <div>
                    <label className="text-xs font-medium text-gray-600 mb-1 block">Nume</label>
                    <input className={ic} value={fd.last_name} onChange={e => set('last_name', e.target.value)} placeholder="Popescu" />
                  </div>
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">Nume utilizator * <span className="font-normal text-gray-400">(pentru logare)</span></label>
                  <input className={ic} value={fd.username} onChange={e => set('username', e.target.value)} placeholder="ex: robert" required autoCapitalize="off" autoCorrect="off" />
                  {fd.username.trim() && (
                    <p className="text-[11px] text-emerald-600 mt-1">Se loghează cu: <b>{fd.username.trim().toLowerCase().replace(/\s+/g, '.')}</b></p>
                  )}
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">Email contact <span className="font-normal text-gray-400">(opțional)</span></label>
                  <input className={ic} type="email" value={fd.email} onChange={e => set('email', e.target.value)} placeholder="agent@agentie.ro" />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs font-medium text-gray-600 mb-1 block">Telefon</label>
                    <input className={ic} value={fd.phone} onChange={e => set('phone', e.target.value)} placeholder="07xx xxx xxx" />
                  </div>
                  <div>
                    <label className="text-xs font-medium text-gray-600 mb-1 block">{isEdit ? 'Parolă nouă (lasă gol)' : 'Parolă *'}</label>
                    <input className={ic} type="password" value={fd.password} onChange={e => set('password', e.target.value)} placeholder="••••••••" required={!isEdit} />
                  </div>
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">URL poză profil</label>
                  <input className={ic} value={fd.avatar_url} onChange={e => set('avatar_url', e.target.value)} placeholder="https://..." />
                </div>
              </div>
            )}
          </div>

          {/* Rol si departament */}
          <div>
            <Sec id="role" title="2. Rol & Departament" />
            {openSec.role && (
              <div className="space-y-3">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs font-medium text-gray-600 mb-1 block">Funcție</label>
                    <input className={ic} value={fd.job_title} onChange={e => set('job_title', e.target.value)} placeholder="Agent imobiliar" />
                  </div>
                  <div>
                    <label className="text-xs font-medium text-gray-600 mb-1 block">Departament</label>
                    <input className={ic} value={fd.department} onChange={e => set('department', e.target.value)} placeholder="Rezidențial" />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-xs font-medium text-gray-600 mb-1 block">Rol *</label>
                    <select className={ic} value={fd.role} onChange={e => onRoleChange(e.target.value)}>
                      {Object.entries(ROLES).map(([v, l]) => <option key={v} value={v}>{l}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="text-xs font-medium text-gray-600 mb-1 block">Status</label>
                    <select className={ic} value={fd.status} onChange={e => set('status', e.target.value)}>
                      <option value="activ">Activ</option>
                      <option value="inactiv">Inactiv</option>
                    </select>
                  </div>
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">Data angajării</label>
                  <input className={ic} type="date" value={fd.hired_at || ''} onChange={e => set('hired_at', e.target.value)} />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-600 mb-1 block">Notițe interne</label>
                  <textarea className={ic} rows={2} value={fd.notes} onChange={e => set('notes', e.target.value)} placeholder="Observații despre agent..." />
                </div>
              </div>
            )}
          </div>

          {/* Permisiuni */}
          <div>
            <Sec id="perms" title="3. Permisiuni" />
            {openSec.perms && (
              <div className="overflow-x-auto">
                <p className="text-xs text-gray-500 mb-2">Bifate automat după rol — poți personaliza.</p>
                <table className="min-w-[680px] w-full text-xs border-collapse">
                  <thead>
                    <tr className="bg-gray-50">
                      <th className="sticky left-0 z-10 bg-gray-50 text-left py-2 px-3 font-semibold text-gray-600">Modul</th>
                      {ACTIONS.map(a => <th key={a} className="py-2 px-2 font-semibold text-gray-600 text-center capitalize">{a}</th>)}
                    </tr>
                  </thead>
                  <tbody>
                    {MODULES.map(m => (
                      <tr key={m.key} className="border-t border-gray-100">
                        <td className="sticky left-0 bg-white py-2 px-3 font-medium text-gray-700">{m.label}</td>
                        {ACTIONS.map(a => (
                          <td key={a} className="py-2 px-2 text-center">
                            <button type="button" onClick={() => togglePerm(m.key, a)}
                              className={`w-5 h-5 rounded border-2 flex items-center justify-center mx-auto transition-colors ${perms[m.key]?.[a] ? 'bg-emerald-500 border-emerald-500' : 'border-gray-300 hover:border-emerald-300'}`}>
                              {perms[m.key]?.[a] && <Check size={11} className="text-white" />}
                            </button>
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {error && <div className="bg-red-50 border border-red-200 rounded-lg p-3 text-red-800 text-sm">{error}</div>}
        </form>

        <div className="border-t px-6 py-4 flex justify-end gap-3 flex-shrink-0">
          <button type="button" onClick={onClose} className="px-4 py-2 text-gray-600 hover:bg-gray-50 rounded-lg border text-sm">Anulează</button>
          <button onClick={handleSubmit} disabled={loading}
            className="px-5 py-2 text-white rounded-lg font-medium text-sm disabled:opacity-50 flex items-center gap-2"
            style={{ backgroundColor: '#0E6B54' }}>
            {loading ? 'Se salvează...' : isEdit ? 'Salvează' : 'Creează Agent'}
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Profile Modal ─────────────────────────────────────────────────────────────
function ProfileModal({ member, onClose, onEdit }: { member: Member; onClose: () => void; onEdit: () => void }) {
  return (
    <div className="mobile-dialog-backdrop fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="mobile-dialog-panel bg-white rounded-xl w-full max-w-lg max-h-[90vh] overflow-y-auto shadow-xl">
        {/* Header */}
        <div className="px-6 pb-6">
          <div className="flex items-center justify-between pt-5 mb-4">
            <div className="flex items-center gap-4">
              <div className="rounded-full shadow-md" style={{ border: '3px solid #0E6B54' }}>
                <Avatar member={member} size={16} />
              </div>
              <div>
                <p className="font-bold text-gray-900 text-lg leading-tight">{member.full_name || member.email}</p>
                <p className="text-sm text-gray-500">{member.job_title || ''}</p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <button onClick={onEdit}
                className="flex items-center gap-1.5 px-3 py-1.5 text-sm font-medium rounded-lg border border-gray-200 hover:bg-gray-50 text-gray-600">
                <Edit2 size={14} />Editează
              </button>
              <button onClick={onClose} className="p-1.5 hover:bg-gray-100 rounded-lg text-gray-500"><X size={18} /></button>
            </div>
          </div>

          <div className="flex items-center gap-2 flex-wrap mb-4">
            <RoleBadge role={member.role} />
            <StatusBadge status={member.status} />
            {member.department && <span className="text-xs text-gray-500 bg-gray-100 px-2 py-0.5 rounded-full">{member.department}</span>}
          </div>

          {/* Contact */}
          <div className="grid grid-cols-2 gap-3 mb-4">
            <InfoRow icon={<Key size={14} />} label="Utilizator (login)" value={member.username || '— nesetat'} />
            <InfoRow icon={<Mail size={14} />} label="Email contact" value={member.contact_email || member.email || '—'} />
            <InfoRow icon={<Phone size={14} />} label="Telefon" value={member.phone || '—'} />
            <InfoRow icon={<Calendar size={14} />} label="Angajat" value={formatDate(member.hired_at)} />
            <InfoRow icon={<Clock size={14} />} label="Ultima conectare" value={formatRelative(member.last_sign_in_at)} />
            <InfoRow icon={<Calendar size={14} />} label="Cont creat" value={formatDate(member.created_at)} />
          </div>

          {/* Stats */}
          <div className="grid grid-cols-3 gap-3 mb-4">
            <StatCard icon={<Home size={18} />} label="Prop. active" value={member.stats.properties_active} color="text-emerald-600" />
            <StatCard icon={<CheckCircle size={18} />} label="Tranzacții" value={member.stats.properties_sold} color="text-blue-600" />
            <StatCard icon={<Target size={18} />} label="Clienți" value={member.stats.clients} color="text-purple-600" />
          </div>

          {/* Notes */}
          {member.notes && (
            <div className="bg-amber-50 border border-amber-200 rounded-lg p-3 text-sm text-gray-700">
              <p className="font-medium text-amber-700 mb-1 text-xs">Notițe interne</p>
              {member.notes}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function InfoRow({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="flex items-start gap-2">
      <span className="text-gray-400 mt-0.5 flex-shrink-0">{icon}</span>
      <div>
        <p className="text-xs text-gray-400">{label}</p>
        <p className="text-sm text-gray-800 font-medium">{value}</p>
      </div>
    </div>
  );
}

function StatCard({ icon, label, value, color }: { icon: React.ReactNode; label: string; value: number; color: string }) {
  return (
    <div className="bg-gray-50 rounded-xl p-3 text-center">
      <span className={`${color} flex justify-center mb-1`}>{icon}</span>
      <p className="text-2xl font-black text-gray-900">{value}</p>
      <p className="text-xs text-gray-500">{label}</p>
    </div>
  );
}

// ── Delete Confirm Dialog ─────────────────────────────────────────────────────
function DeleteDialog({ member, members, token, onClose, onSuccess }: {
  member: Member; members: Member[]; token: string; onClose: () => void; onSuccess: () => void;
}) {
  const [reassignTo, setReassignTo] = useState('');
  const [confirm, setConfirm] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const others = members.filter(m => m.id !== member.id);

  const handleDelete = async () => {
    if (confirm !== member.email) { setError('Scrie emailul agentului pentru confirmare'); return; }
    setLoading(true);
    try {
      const res = await fetch(`/api/team/members/${member.id}`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ reassign_to_user_id: reassignTo || null }),
      });
      const d = await res.json();
      if (!res.ok) throw new Error(d.error);
      onSuccess();
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Eroare');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="mobile-dialog-backdrop fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4">
      <div className="mobile-dialog-panel bg-white rounded-xl w-full max-w-md shadow-2xl p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-red-100 rounded-full flex items-center justify-center flex-shrink-0">
            <AlertTriangle size={20} className="text-red-600" />
          </div>
          <div>
            <h3 className="font-bold text-gray-900">Dezactivează agent</h3>
            <p className="text-sm text-gray-500">Contul este blocat, iar istoricul este păstrat.</p>
          </div>
        </div>

        <div className="bg-red-50 border border-red-200 rounded-lg p-3 mb-4 text-sm text-red-800">
          Vei dezactiva <strong>{member.full_name || member.email}</strong>, cu <strong>{member.stats.properties_active} proprietăți active</strong> și <strong>{member.stats.clients} clienți</strong>.
        </div>

        {others.length > 0 && (
          <div className="mb-4">
            <label className="text-sm font-medium text-gray-700 mb-1 block">Mută datele la agentul:</label>
            <select className={ic} value={reassignTo} onChange={e => setReassignTo(e.target.value)}>
              <option value="">— Nu muta (lasă nealocat) —</option>
              {others.map(m => <option key={m.user_id} value={m.user_id}>{m.full_name || m.email}</option>)}
            </select>
          </div>
        )}

        <div className="mb-4">
          <label className="text-sm font-medium text-gray-700 mb-1 block">
            Scrie <span className="font-mono text-red-600">{member.email}</span> pentru confirmare:
          </label>
          <input className={ic} value={confirm} onChange={e => setConfirm(e.target.value)} placeholder={member.email} />
        </div>

        {error && <div className="bg-red-50 border border-red-200 rounded-lg p-2 text-red-800 text-sm mb-3">{error}</div>}

        <div className="flex justify-end gap-3">
          <button onClick={onClose} className="px-4 py-2 text-gray-600 border rounded-lg hover:bg-gray-50 text-sm">Anulează</button>
          <button onClick={handleDelete} disabled={loading || confirm !== member.email}
            className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 disabled:opacity-40 text-sm font-medium">
            {loading ? 'Se dezactivează...' : 'Dezactivează contul'}
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Permissions Matrix ────────────────────────────────────────────────────────
function PermissionsMatrix() {
  const [selectedRole, setSelectedRole] = useState('admin');
  const perms = DEFAULT_PERMISSIONS[selectedRole] || {};
  return (
    <div>
      <div className="flex items-center gap-3 mb-4 flex-wrap">
        {Object.entries(ROLES).map(([v, l]) => (
          <button key={v} onClick={() => setSelectedRole(v)}
            className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${selectedRole === v ? 'text-white' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'}`}
            style={selectedRole === v ? { backgroundColor: '#0E6B54' } : {}}>
            {l}
          </button>
        ))}
      </div>
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-[680px] w-full text-sm">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left py-3 px-4 font-semibold text-gray-700 w-40">Modul</th>
                {ACTIONS.map(a => (
                  <th key={a} className="py-3 px-3 text-center font-semibold text-gray-600 capitalize">{a}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {MODULES.map((m, i) => (
                <tr key={m.key} className={i % 2 === 0 ? 'bg-white' : 'bg-gray-50/50'}>
                  <td className="py-3 px-4 font-medium text-gray-800">{m.label}</td>
                  {ACTIONS.map(a => (
                    <td key={a} className="py-3 px-3 text-center">
                      {perms[m.key]?.[a]
                        ? <CheckCircle size={18} className="text-emerald-500 mx-auto" />
                        : <XCircle size={18} className="text-gray-300 mx-auto" />}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      <p className="text-xs text-gray-400 mt-2">Permisiunile pot fi personalizate individual la editarea fiecărui agent.</p>
    </div>
  );
}

// ── Activity Tab ──────────────────────────────────────────────────────────────
function ActivityTab({ token }: { token: string }) {
  const [events, setEvents] = useState<ActivityEvent[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/team/activity', { headers: { Authorization: `Bearer ${token}` } })
      .then(r => r.json())
      .then(d => setEvents(d.events || []))
      .finally(() => setLoading(false));
  }, [token]);

  if (loading) return <div className="text-center py-10 text-gray-400">Se încarcă activitatea...</div>;
  if (events.length === 0) return <div className="text-center py-10 text-gray-400">Nicio activitate înregistrată.</div>;

  const typeIcon: Record<string, React.ReactNode> = {
    property: <Home size={14} className="text-emerald-600" />,
    demand: <Target size={14} className="text-blue-600" />,
    contact: <Users size={14} className="text-purple-600" />,
  };
  const typeBg: Record<string, string> = {
    property: 'bg-emerald-50 border-emerald-200',
    demand: 'bg-blue-50 border-blue-200',
    contact: 'bg-purple-50 border-purple-200',
  };

  return (
    <div className="space-y-2">
      {events.map(ev => (
        <div key={ev.id} className={`flex items-start gap-3 p-3 rounded-lg border ${typeBg[ev.type] || 'bg-gray-50 border-gray-200'}`}>
          <div className="mt-0.5 w-7 h-7 rounded-full bg-white border flex items-center justify-center flex-shrink-0">
            {typeIcon[ev.type] || <Activity size={14} className="text-gray-500" />}
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-medium text-gray-900">{ev.label}</p>
            <p className="text-xs text-gray-500 mt-0.5">
              <span className="font-medium text-gray-600">{ev.agent_name}</span>
              {' · '}{formatRelative(ev.created_at)}
              {ev.entity_code && <span className="ml-2 font-mono text-gray-400">{ev.entity_code}</span>}
            </p>
          </div>
        </div>
      ))}
    </div>
  );
}

// ── Main Page ─────────────────────────────────────────────────────────────────
export default function TeamPage() {
  const { can } = useAuth();
  const [members, setMembers] = useState<Member[]>([]);
  const [stats, setStats] = useState<TeamStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [token, setToken] = useState('');
  const [tab, setTab] = useState<'members' | 'activity' | 'permissions'>('members');
  const [search, setSearch] = useState('');
  const [filterRole, setFilterRole] = useState('');
  const [filterStatus, setFilterStatus] = useState('');

  const [dialogMember, setDialogMember] = useState<Member | null | undefined>(undefined);
  const [profileMember, setProfileMember] = useState<Member | null>(null);
  const [deleteMember, setDeleteMember] = useState<Member | null>(null);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (session) {
        setToken(session.access_token);
        fetchAll(session.access_token);
      }
    });
  }, []);

  const fetchAll = async (tok: string) => {
    setLoading(true);
    try {
      const [mRes, sRes] = await Promise.all([
        fetch('/api/team/members', { headers: { Authorization: `Bearer ${tok}` } }),
        fetch('/api/team/stats', { headers: { Authorization: `Bearer ${tok}` } }),
      ]);
      const mData = await mRes.json();
      const sData = await sRes.json();
      if (!mRes.ok) throw new Error(mData.error);
      setMembers(mData.members || []);
      if (sRes.ok) setStats(sData);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Eroare');
    } finally {
      setLoading(false);
    }
  };

  const filtered = members.filter(m => {
    const q = search.toLowerCase();
    const matchQ = !q || m.full_name.toLowerCase().includes(q) || m.email.toLowerCase().includes(q) || m.job_title.toLowerCase().includes(q) || m.phone.includes(q);
    const matchRole = !filterRole || m.role === filterRole;
    const matchStatus = !filterStatus || m.status === filterStatus;
    return matchQ && matchRole && matchStatus;
  });

  const TABS = [
    { id: 'members', label: 'Membri', icon: <Users size={16} /> },
    { id: 'activity', label: 'Activitate', icon: <Activity size={16} /> },
    { id: 'permissions', label: 'Permisiuni', icon: <Shield size={16} /> },
  ] as const;

  return (
    <ProtectedLayout module="team">
      <div className="p-4 sm:p-6 max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
          <div>
            <h1 className="text-3xl font-bold" style={{ color: '#0E6B54' }}>Echipă</h1>
            <p className="text-sm text-gray-500 mt-1">{members.length} membri în agenție</p>
          </div>
          {can('team', 'create') && (
            <button
              onClick={() => setDialogMember(null)}
              className="mobile-touch-target flex w-full items-center justify-center gap-2 px-4 py-2.5 rounded-lg font-medium text-white hover:opacity-90 transition-colors sm:w-auto"
              style={{ backgroundColor: '#0E6B54' }}>
              <UserPlus size={18} />Adaugă Agent
            </button>
          )}
        </div>

        {/* Stats */}
        {stats && (
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
            {[
              { label: 'Total agenți', value: stats.total_members, icon: <Users size={20} />, color: 'text-blue-600', bg: 'bg-blue-50' },
              { label: 'Prop. active', value: stats.active_properties, icon: <Home size={20} />, color: 'text-emerald-600', bg: 'bg-emerald-50' },
              { label: 'Tranzacționate', value: stats.sold_properties, icon: <CheckCircle size={20} />, color: 'text-purple-600', bg: 'bg-purple-50' },
              { label: 'Clienți totali', value: stats.total_clients, icon: <Target size={20} />, color: 'text-orange-600', bg: 'bg-orange-50' },
              { label: 'Medie prop./agent', value: stats.avg_properties_per_agent, icon: <BarChart3 size={20} />, color: 'text-pink-600', bg: 'bg-pink-50' },
            ].map(s => (
              <div key={s.label} className="bg-white rounded-xl border border-gray-100 shadow-sm p-4">
                <div className={`w-9 h-9 rounded-lg ${s.bg} flex items-center justify-center ${s.color} mb-2`}>{s.icon}</div>
                <p className="text-2xl font-black text-gray-900">{s.value}</p>
                <p className="text-xs text-gray-500">{s.label}</p>
              </div>
            ))}
          </div>
        )}

        {/* Tabs */}
        <div className="flex max-w-full gap-1 overflow-x-auto bg-gray-100 rounded-xl p-1 mb-6 sm:w-fit">
          {TABS.filter(t => t.id !== 'permissions' || can('team', 'manage_permissions')).map(t => (
            <button key={t.id} onClick={() => setTab(t.id)}
              className={`mobile-touch-target flex shrink-0 items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${tab === t.id ? 'bg-white text-gray-900 shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}>
              {t.icon}{t.label}
            </button>
          ))}
        </div>

        {/* Members Tab */}
        {tab === 'members' && (
          <>
            {/* Filters */}
            <div className="bg-white rounded-xl border border-gray-200 p-4 mb-4 flex flex-wrap gap-3">
              <div className="relative flex-1 min-w-48">
                <Search className="absolute left-3 top-2.5 text-gray-400" size={15} />
                <input className="w-full pl-9 pr-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
                  placeholder="Caută după nume, email, telefon..."
                  value={search} onChange={e => setSearch(e.target.value)} />
              </div>
              <select className="px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none"
                value={filterRole} onChange={e => setFilterRole(e.target.value)}>
                <option value="">Toate rolurile</option>
                {Object.entries(ROLES).map(([v, l]) => <option key={v} value={v}>{l}</option>)}
              </select>
              <select className="px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none"
                value={filterStatus} onChange={e => setFilterStatus(e.target.value)}>
                <option value="">Toate statusurile</option>
                <option value="activ">Activi</option>
                <option value="inactiv">Inactivi</option>
              </select>
            </div>

            {loading ? (
              <div className="text-center py-16 text-gray-400">Se încarcă echipa...</div>
            ) : error ? (
              <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-red-800">{error}</div>
            ) : filtered.length === 0 ? (
              <div className="text-center py-16">
                <Users size={48} className="mx-auto text-gray-200 mb-4" />
                <p className="text-gray-500 font-medium">Niciun agent găsit</p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {filtered.map(m => (
                  <div key={m.id}
                    className="bg-white rounded-xl border border-gray-200 hover:border-emerald-300 hover:shadow-md transition-all cursor-pointer overflow-hidden"
                    onClick={() => setProfileMember(m)}>
                    <div className="p-5">
                      <div className="flex items-start justify-between gap-3 mb-3">
                        <div className="flex items-center gap-3">
                          <Avatar member={m} size={12} />
                          <div className="min-w-0">
                            <p className="font-bold text-gray-900 text-sm truncate">{m.full_name || m.email}</p>
                            <p className="text-xs text-gray-400 truncate">{m.email}</p>
                          </div>
                        </div>
                        <div onClick={e => e.stopPropagation()} className="flex gap-1 flex-shrink-0">
                          {can('team', 'edit') && (
                            <button onClick={() => setDialogMember(m)}
                              className="p-1.5 text-gray-400 hover:text-emerald-600 hover:bg-emerald-50 rounded-lg transition-colors"
                              title="Editează">
                              <Edit2 size={15} />
                            </button>
                          )}
                          {can('team', 'delete') && (
                            <button onClick={() => setDeleteMember(m)}
                              className="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                              title="Dezactivează">
                              <Trash2 size={15} />
                            </button>
                          )}
                        </div>
                      </div>

                      <div className="flex flex-wrap gap-1.5 mb-3">
                        <RoleBadge role={m.role} />
                        <StatusBadge status={m.status} />
                        {m.job_title && (
                          <span className="text-xs text-gray-500 bg-gray-50 px-2 py-0.5 rounded-full">{m.job_title}</span>
                        )}
                      </div>

                      <div className="flex items-center gap-1.5 text-xs text-gray-500 mb-3">
                        {m.phone && <><Phone size={11} /><span>{m.phone}</span><span className="mx-1">·</span></>}
                        <Clock size={11} />
                        <span>{formatRelative(m.last_sign_in_at)}</span>
                      </div>

                      <div className="grid grid-cols-3 gap-2 pt-3 border-t border-gray-100">
                        <div className="text-center">
                          <p className="text-lg font-black text-gray-900">{m.stats.properties_active}</p>
                          <p className="text-xs text-gray-400">Active</p>
                        </div>
                        <div className="text-center">
                          <p className="text-lg font-black text-gray-900">{m.stats.properties_sold}</p>
                          <p className="text-xs text-gray-400">Vândute</p>
                        </div>
                        <div className="text-center">
                          <p className="text-lg font-black text-gray-900">{m.stats.clients}</p>
                          <p className="text-xs text-gray-400">Clienți</p>
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </>
        )}

        {/* Activity Tab */}
        {tab === 'activity' && token && (
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h2 className="font-bold text-gray-900 mb-4 flex items-center gap-2"><Activity size={18} className="text-emerald-600" />Activitate recentă</h2>
            <ActivityTab token={token} />
          </div>
        )}

        {/* Permissions Tab */}
        {tab === 'permissions' && can('team', 'manage_permissions') && (
          <div className="bg-white rounded-xl border border-gray-200 p-5">
            <h2 className="font-bold text-gray-900 mb-1 flex items-center gap-2"><Shield size={18} className="text-emerald-600" />Matrice permisiuni</h2>
            <p className="text-sm text-gray-500 mb-4">Permisiunile implicite per rol. Pot fi personalizate individual.</p>
            <PermissionsMatrix />
          </div>
        )}
      </div>

      {/* Add / Edit Dialog */}
      {dialogMember !== undefined && (
        <AgentDialog
          member={dialogMember}
          members={members}
          token={token}
          onClose={() => setDialogMember(undefined)}
          onSuccess={() => fetchAll(token)}
        />
      )}

      {/* Profile Modal */}
      {profileMember && (
        <ProfileModal
          member={profileMember}
          onClose={() => setProfileMember(null)}
          onEdit={() => { setDialogMember(profileMember); setProfileMember(null); }}
        />
      )}

      {/* Delete Dialog */}
      {deleteMember && (
        <DeleteDialog
          member={deleteMember}
          members={members}
          token={token}
          onClose={() => setDeleteMember(null)}
          onSuccess={() => fetchAll(token)}
        />
      )}
    </ProtectedLayout>
  );
}
