export const JUDETE: string[] = [
  'Alba', 'Arad', 'Argeș', 'Bacău', 'Bihor', 'Bistrița-Năsăud',
  'Botoșani', 'Brăila', 'Brașov', 'București', 'Buzău', 'Călărași',
  'Cluj', 'Constanța', 'Covasna', 'Dâmbovița', 'Dolj', 'Galați',
  'Giurgiu', 'Gorj', 'Harghita', 'Hunedoara', 'Ialomița', 'Iași',
  'Ilfov', 'Maramureș', 'Mehedinți', 'Mureș', 'Neamț', 'Olt',
  'Prahova', 'Satu Mare', 'Sălaj', 'Sibiu', 'Suceava', 'Teleorman',
  'Timiș', 'Tulcea', 'Vaslui', 'Vâlcea', 'Vrancea',
];

export const ORASE_BY_JUDET: Record<string, string[]> = {
  'Alba': ['Alba Iulia', 'Sebeș', 'Blaj', 'Aiud', 'Cugir', 'Câmpeni', 'Abrud', 'Zlatna', 'Ocna Mureș'],
  'Arad': ['Arad', 'Ineu', 'Lipova', 'Nădlac', 'Curtici', 'Pâncota', 'Sebiș', 'Chișineu-Criș'],
  'Argeș': ['Pitești', 'Câmpulung', 'Curtea de Argeș', 'Mioveni', 'Costești', 'Topoloveni', 'Ștefănești'],
  'Bacău': ['Bacău', 'Onești', 'Moinești', 'Comănești', 'Buhuși', 'Slănic Moldova', 'Dărmănești'],
  'Bihor': ['Oradea', 'Salonta', 'Beiuș', 'Marghita', 'Săcueni', 'Aleșd', 'Ștei', 'Nucet', 'Vașcău'],
  'Bistrița-Năsăud': ['Bistrița', 'Năsăud', 'Beclean', 'Sângeorz-Băi'],
  'Botoșani': ['Botoșani', 'Dorohoi', 'Darabani', 'Săveni', 'Flămânzi', 'Ștefănești'],
  'Brăila': ['Brăila', 'Ianca', 'Făurei', 'Însurăței'],
  'Brașov': ['Brașov', 'Săcele', 'Zărnești', 'Codlea', 'Predeal', 'Râșnov', 'Sinaia', 'Ghimbav', 'Victoria', 'Rupea', 'Făgăraș'],
  'București': ['București', 'Sector 1', 'Sector 2', 'Sector 3', 'Sector 4', 'Sector 5', 'Sector 6'],
  'Buzău': ['Buzău', 'Râmnicu Sărat', 'Pogoanele', 'Nehoiu', 'Pătârlagele'],
  'Călărași': ['Călărași', 'Oltenița', 'Lehliu Gară', 'Fundulea'],
  'Cluj': ['Cluj-Napoca', 'Turda', 'Dej', 'Gherla', 'Huedin', 'Florești', 'Câmpia Turzii', 'Apahida', 'Baciu'],
  'Constanța': ['Constanța', 'Mangalia', 'Medgidia', 'Năvodari', 'Cernavodă', 'Ovidiu', 'Eforie Nord', 'Eforie Sud', 'Techirghiol', 'Murfatlar'],
  'Covasna': ['Sfântu Gheorghe', 'Târgu Secuiesc', 'Covasna', 'Baraolt', 'Întorsura Buzăului'],
  'Dâmbovița': ['Târgoviște', 'Moreni', 'Pucioasa', 'Găești', 'Titu'],
  'Dolj': ['Craiova', 'Băilești', 'Calafat', 'Filiaș', 'Segarcea', 'Dăbuleni', 'Bechet'],
  'Galați': ['Galați', 'Tecuci', 'Târgu Bujor', 'Berești'],
  'Giurgiu': ['Giurgiu', 'Bolintin-Vale', 'Mihăilești'],
  'Gorj': ['Târgu Jiu', 'Motru', 'Rovinari', 'Bumbești-Jiu', 'Tismana', 'Novaci'],
  'Harghita': ['Miercurea Ciuc', 'Odorheiu Secuiesc', 'Gheorgheni', 'Toplița', 'Băile Tușnad', 'Vlăhița'],
  'Hunedoara': ['Deva', 'Hunedoara', 'Brad', 'Orăștie', 'Petroșani', 'Lupeni', 'Vulcan', 'Simeria', 'Uricani'],
  'Ialomița': ['Slobozia', 'Fetești', 'Urziceni', 'Amara', 'Căzănești'],
  'Iași': ['Iași', 'Pașcani', 'Hârlău', 'Târgu Frumos', 'Podu Iloaiei'],
  'Ilfov': ['Buftea', 'Voluntari', 'Popești-Leordeni', 'Pantelimon', 'Otopeni', 'Chitila', 'Măgurele', 'Bragadiru', 'Tunari'],
  'Maramureș': ['Baia Mare', 'Sighetu Marmației', 'Borșa', 'Vișeu de Sus', 'Târgu Lăpuș', 'Cavnic'],
  'Mehedinți': ['Drobeta-Turnu Severin', 'Orșova', 'Strehaia', 'Vânju Mare', 'Baia de Aramă'],
  'Mureș': ['Târgu Mureș', 'Sighișoara', 'Reghin', 'Târnăveni', 'Luduș', 'Sovata', 'Iernut'],
  'Neamț': ['Piatra Neamț', 'Roman', 'Târgu Neamț', 'Bicaz', 'Roznov'],
  'Olt': ['Slatina', 'Caracal', 'Balș', 'Corabia', 'Drăgănești-Olt', 'Scornicești'],
  'Prahova': ['Ploiești', 'Câmpina', 'Sinaia', 'Bușteni', 'Azuga', 'Mizil', 'Urlați', 'Băicoi', 'Vălenii de Munte'],
  'Satu Mare': ['Satu Mare', 'Carei', 'Negrești-Oaș', 'Tășnad', 'Ardud'],
  'Sălaj': ['Zalău', 'Șimleu Silvaniei', 'Cehu Silvaniei', 'Jibou'],
  'Sibiu': ['Sibiu', 'Mediaș', 'Cisnădie', 'Miercurea Sibiului', 'Avrig', 'Agnita', 'Copșa Mică', 'Ocna Sibiului'],
  'Suceava': ['Suceava', 'Rădăuți', 'Fălticeni', 'Câmpulung Moldovenesc', 'Vatra Dornei', 'Gura Humorului', 'Siret'],
  'Teleorman': ['Alexandria', 'Roșiorii de Vede', 'Turnu Măgurele', 'Zimnicea', 'Videle'],
  'Timiș': ['Timișoara', 'Lugoj', 'Sânnicolau Mare', 'Jimbolia', 'Deta', 'Buziaș', 'Recaș', 'Făget'],
  'Tulcea': ['Tulcea', 'Sulina', 'Babadag', 'Măcin', 'Isaccea'],
  'Vaslui': ['Vaslui', 'Bârlad', 'Huși', 'Negrești'],
  'Vâlcea': ['Râmnicu Vâlcea', 'Drăgășani', 'Brezoi', 'Băile Govora', 'Băile Olănești', 'Ocnele Mari', 'Horezu'],
  'Vrancea': ['Focșani', 'Adjud', 'Mărășești', 'Panciu', 'Odobești'],
};
