export const JUDETE: string[] = [
  'Alba', 'Arad', 'Argeș', 'Bacău', 'Bihor', 'Bistrița-Năsăud',
  'Botoșani', 'Brăila', 'Brașov', 'București', 'Buzău', 'Călărași',
  'Cluj', 'Constanța', 'Covasna', 'Dâmbovița', 'Dolj', 'Galați',
  'Giurgiu', 'Gorj', 'Harghita', 'Hunedoara', 'Ialomița', 'Iași',
  'Ilfov', 'Maramureș', 'Mehedinți', 'Mureș', 'Neamț', 'Olt',
  'Prahova', 'Satu Mare', 'Sălaj', 'Sibiu', 'Suceava', 'Teleorman',
  'Timiș', 'Tulcea', 'Vaslui', 'Vâlcea', 'Vrancea',
];

export const ORASE_BY_JUDET: Record<string, string[]> = {
  'Alba': [
    'Alba Iulia', 'Sebeș', 'Blaj', 'Aiud', 'Cugir', 'Câmpeni', 'Abrud', 'Zlatna', 'Ocna Mureș',
    'Baia de Arieș', 'Teiuș', 'Mihăileni', 'Ciuruleasa', 'Roșia Montană', 'Bucium',
    'Hopârta', 'Ighiu', 'Galda de Jos', 'Meteș', 'Berghin', 'Cricău', 'Crăciunelu de Jos',
    'Gârbova', 'Lopadea Nouă', 'Mirăslău', 'Noșlac', 'Rimetea', 'Sântimbru', 'Unirea',
    'Vințu de Jos', 'Vidra', 'Mogoș', 'Ponor', 'Lupșa', 'Poiana Vadului', 'Sălciua',
    'Scărișoara', 'Albac', 'Arieșeni', 'Bistra', 'Gârda de Sus',
  ],
  'Arad': [
    'Arad', 'Ineu', 'Lipova', 'Nădlac', 'Curtici', 'Pâncota', 'Sebiș', 'Chișineu-Criș',
    'Sântana', 'Pecica', 'Vladimirescu', 'Ghioroc', 'Pilu', 'Zărand', 'Buteni', 'Hălmagiu',
    'Vărșand', 'Dorobanți', 'Fântânele', 'Olari', 'Șiria', 'Șilindia', 'Conop', 'Dezna',
    'Gurahonț', 'Moneasa', 'Seleuș', 'Tarnova', 'Beliu', 'Bârzava', 'Bocsig',
  ],
  'Argeș': [
    'Pitești', 'Câmpulung', 'Curtea de Argeș', 'Mioveni', 'Costești', 'Topoloveni', 'Ștefănești',
    'Mihăești', 'Morărești', 'Negrași', 'Vedea', 'Rucăr', 'Muscel', 'Bascov', 'Bradu',
    'Călinești', 'Căteasca', 'Ciomagești', 'Cocu', 'Davidești', 'Dobrești', 'Godeni',
    'Hârsești', 'Izvoru', 'Leordeni', 'Maracineni', 'Merișani', 'Mihăilești', 'Mozăceni',
    'Nucșoara', 'Pietroșani', 'Popești', 'Slobozia', 'Stolnici', 'Suseni', 'Uda', 'Ungheni',
  ],
  'Bacău': [
    'Bacău', 'Onești', 'Moinești', 'Comănești', 'Buhuși', 'Slănic Moldova', 'Dărmănești',
    'Târgu Ocna', 'Buhoci', 'Cleja', 'Colonești', 'Corbasca', 'Filipești', 'Gura Văii',
    'Hemeiuș', 'Horgești', 'Letea Veche', 'Luizi-Călugăra', 'Mărgineni', 'Nicolești',
    'Podu Turcului', 'Răcăciuni', 'Roșiori', 'Sascut', 'Secuieni', 'Ștefan cel Mare',
    'Tămășeni', 'Ungureni', 'Valea Seacă', 'Verești', 'Zemeș',
  ],
  'Bihor': [
    'Oradea', 'Salonta', 'Beiuș', 'Marghita', 'Săcueni', 'Aleșd', 'Ștei', 'Nucet', 'Vașcău',
    'Vâșcău', 'Dobrești', 'Drăgănești', 'Budureasa', 'Bulz', 'Căbești', 'Cefa', 'Cetariu',
    'Girișu de Criș', 'Hidișelu de Sus', 'Holod', 'Lazuri de Bihor', 'Lăzăreni', 'Nojorid',
    'Paleu', 'Roșiori', 'Sânmartin', 'Sântandrei', 'Sâniob', 'Sânnicolau Român', 'Sârbi',
    'Sudrigiu', 'Suplacu de Barcău', 'Tămășeu', 'Tulca', 'Uileacu de Beiuș',
  ],
  'Bistrița-Năsăud': [
    'Bistrița', 'Năsăud', 'Beclean', 'Sângeorz-Băi',
    'Bistrița Bârgăului', 'Braniștea', 'Budacu de Jos', 'Căianu Mic', 'Cetate',
    'Chiuza', 'Ciceu-Giurgești', 'Coșbuc', 'Dumitra', 'Feldru', 'Galatii Bistriței',
    'Ilva Mare', 'Ilva Mică', 'Josenii Bârgăului', 'Lechința', 'Leșu', 'Livezile',
    'Lunca Ilvei', 'Maieru', 'Matei', 'Mărișelu', 'Milaș', 'Monor', 'Negrilești',
    'Nimigea', 'Nușeni', 'Prundu Bârgăului', 'Rebrișoara', 'Rodna', 'Runcu Salvei',
    'Salva', 'Sânmihaiu de Câmpie', 'Șieu', 'Șieu-Măgheruș', 'Șieu-Odorhei',
    'Șieuț', 'Șintereag', 'Telciu', 'Tiha Bârgăului', 'Uriu', 'Urmeniș',
  ],
  'Botoșani': [
    'Botoșani', 'Dorohoi', 'Darabani', 'Săveni', 'Flămânzi', 'Ștefănești',
    'Bucecea', 'Trusești', 'Vorona', 'Albești', 'Avrămeni', 'Bălușeni', 'Blândești',
    'Brăești', 'Concești', 'Coțușca', 'Cristești', 'Dângeni', 'Dersca', 'Dimăcheni',
    'Dobârceni', 'Frumușica', 'George Enescu', 'Havârna', 'Hilișeu-Horia', 'Hudești',
    'Ibănești', 'Leorda', 'Lozna', 'Lunca', 'Mileanca', 'Mihăileni', 'Mihai Eminescu',
    'Mitoc', 'Nicșeni', 'Pomârla', 'Prăjeni', 'Răchiți', 'Rădăuți-Prut', 'Ripiceni',
    'Roma', 'Românești', 'Santa Mare', 'Sendriceni', 'Silistraru', 'Stăuceni',
    'Suharău', 'Șupitca', 'Tudora', 'Ungureni', 'Unțeni', 'Văculești', 'Vlăsinești',
    'Vârfu Câmpului', 'Vlădeni', 'Vorniceni',
  ],
  'Brăila': [
    'Brăila', 'Ianca', 'Făurei', 'Însurăței',
    'Baldovinești', 'Bărăganul', 'Berteștii de Jos', 'Bordei Verde', 'Chiscani', 'Ciocile',
    'Cireșu', 'Dudești', 'Frecăței', 'Galbenu', 'Gemenele', 'Grădiștea', 'Jirlău',
    'Măracineni', 'Mircea Vodă', 'Movila Miresei', 'Racoviță', 'Râmnicelu', 'Romanu',
    'Roșiori', 'Salcia Tudor', 'Scorțaru Nou', 'Sfântu Gheorghe', 'Silistraru',
    'Stăncuța', 'Surdila-Greci', 'Surdila-Găiseanca', 'Tichilești', 'Traian', 'Tudor Vladimirescu',
    'Tufeștii de Jos', 'Ulmu', 'Unirea', 'Urleasca', 'Victoria', 'Vișani', 'Viziru',
    'Vultureni', 'Zăvoaia',
  ],
  'Brașov': [
    // Orașe
    'Brașov', 'Făgăraș', 'Săcele', 'Codlea', 'Zărnești', 'Râșnov', 'Ghimbav', 'Victoria',
    'Predeal', 'Rupea',
    // Comune și sate
    'Apața', 'Augustin', 'Beclean', 'Bod', 'Bogata Olteană', 'Bran', 'Breaza', 'Bunești',
    'Cața', 'Cincu', 'Cobor', 'Comăna', 'Crizbav', 'Dacia', 'Drăguș', 'Dumbrăvița',
    'Feldioara', 'Fundata', 'Grid', 'Hălchiu', 'Hârseni', 'Holbav', 'Homorod',
    'Jibert', 'Lisa', 'Mândra', 'Măieruș', 'Moieciu', 'Moieciu de Jos', 'Moieciu de Sus',
    'Ohaba', 'Ormeniș', 'Paltin', 'Perșani', 'Poiana Mărului', 'Poiana Brașov',
    'Prejmer', 'Racoș', 'Recea', 'Rotbav', 'Sânpetru', 'Șercaia', 'Șinca', 'Șinca Nouă',
    'Șinca Veche', 'Șoarș', 'Tărlungeni', 'Teliu', 'Ticuș', 'Turia', 'Ucea de Jos',
    'Ucea de Sus', 'Ungra', 'Vișri', 'Vlădeni', 'Voila', 'Vulcan',
    // Sate componente importante
    'Bran', 'Simon', 'Șimon', 'Predeluț', 'Tohanu Nou', 'Tohanu Vechi', 'Cristian',
    'Ghimbav', 'Vulcan', 'Cerna', 'Ileni', 'Felmer', 'Dobolii de Jos', 'Homorod',
    'Jimbor', 'Lupșa', 'Mercheașa', 'Sohodol', 'Mateiaș', 'Beia', 'Cuciulata',
    'Dridif', 'Gura Văii', 'Luța', 'Sebeș', 'Olteț', 'Toc', 'Arini', 'Berivoi',
    'Bucium', 'Gura Văii', 'Pojorta', 'Șoarș', 'Calbor', 'Hurez', 'Rucăr',
  ],
  'București': [
    'București', 'Sector 1', 'Sector 2', 'Sector 3', 'Sector 4', 'Sector 5', 'Sector 6',
  ],
  'Buzău': [
    'Buzău', 'Râmnicu Sărat', 'Pogoanele', 'Nehoiu', 'Pătârlagele',
    'Beceni', 'Berca', 'Bisoca', 'Blăjani', 'Boldu', 'Bozioru', 'Brăești',
    'Breaza', 'Buda', 'Căldărăști', 'Calvini', 'Cânești', 'Cătina', 'Cernătești',
    'Chiliile', 'Chiojdu', 'Cislău', 'Cochirleanca', 'Cozieni', 'Glodeanu-Siliștea',
    'Grebănu', 'Gura Teghii', 'Largu', 'Lopătari', 'Luciu', 'Mânzălești',
    'Merei', 'Mihăilești', 'Murești', 'Odăile', 'Padina', 'Pănătău', 'Pardoși',
    'Pietroasele', 'Puiești', 'Racovițeni', 'Robeasca', 'Rusetu', 'Sărulești',
    'Scutelnici', 'Siriu', 'Smeeni', 'Stâlpu', 'Tisău', 'Topliceni', 'Ulmeni',
    'Unguriu', 'Vadu Pașii', 'Vipești', 'Vânători', 'Zărneștii de Slănic', 'Ziduri',
  ],
  'Călărași': [
    'Călărași', 'Oltenița', 'Lehliu Gară', 'Fundulea',
    'Alexandru Odobescu', 'Belciugatele', 'Borcea', 'Chirnogi', 'Clejani',
    'Conțești', 'Curcani', 'Curești', 'Dichiseni', 'Dor Mărunt', 'Dorobanțu',
    'Dragalina', 'Dragos Vodă', 'Frumușani', 'Frumușița', 'Fundeni', 'Grădiștea',
    'Gurbanești', 'Iezeru', 'Independența', 'Jegălia', 'Lehliu', 'Luica', 'Lupșanu',
    'Mânăstirea', 'Mitreni', 'Modelu', 'Nana', 'Nicolae Bălcescu', 'Perișoru',
    'Platarești', 'Radovanu', 'Roseți', 'Sohatu', 'Spanțov', 'Ștefan Vodă',
    'Ștefan cel Mare', 'Tămădău Mare', 'Ulmeni', 'Ulmu', 'Unirea', 'Vasilați', 'Vlad Țepeș',
  ],
  'Cluj': [
    'Cluj-Napoca', 'Turda', 'Dej', 'Gherla', 'Huedin', 'Florești', 'Câmpia Turzii',
    'Apahida', 'Baciu', 'Câțcău', 'Tritenii de Jos',
    'Aiton', 'Aluniș', 'Aschileu', 'Beliș', 'Bobâlna', 'Bonțida', 'Borșa', 'Buza',
    'Căianu', 'Călărași', 'Câțcău', 'Chinteni', 'Chiuiești', 'Ciucea', 'Ciurila',
    'Cojocna', 'Cornești', 'Cuzdrioara', 'Dăbâca', 'Feleacu', 'Fizeșu Gherlii', 'Frata',
    'Gârbău', 'Geaca', 'Gilău', 'Iara', 'Iclod', 'Izvoru Crișului', 'Jichișu de Jos',
    'Jucu', 'Luna', 'Mănăstireni', 'Mărișelu', 'Mărișu', 'Mica', 'Mihai Viteazu',
    'Mintiu Gherlii', 'Mociu', 'Moldovenești', 'Negreni', 'Nireș', 'Ploscoș', 'Poieni',
    'Recea Cristur', 'Rișca', 'Sânpaul', 'Sânmărtin', 'Sic', 'Suatu', 'Tritenii de Jos',
    'Tureni', 'Unguraș', 'Vad', 'Valea Ierii', 'Viișoara', 'Vultureni',
  ],
  'Constanța': [
    'Constanța', 'Mangalia', 'Medgidia', 'Năvodari', 'Cernavodă', 'Ovidiu', 'Eforie',
    'Eforie Nord', 'Eforie Sud', 'Techirghiol', 'Murfatlar', 'Hârșova', 'Negru Vodă',
    'Băneasa', 'Bărăganu', 'Castelu', 'Cobadin', 'Cogealac', 'Comana', 'Corbu',
    'Cumpăna', 'Deleni', 'Dobromir', 'Dumbrăveni', 'Fântânele', 'Gârliciu', 'Grădina',
    'Independența', 'Ion Corvin', 'Istria', 'Limanu', 'Lipnița', 'Lumina', 'Mereni',
    'Mihail Kogălniceanu', 'Mihai Viteazu', 'Mircea Vodă', 'Miriște', 'Nicolae Bălcescu',
    'Oltina', 'Ostrov', 'Pantelimon', 'Pecineaga', 'Peștera', 'Poarta Albă', 'Rasova',
    'Săcele', 'Saligny', 'Saraiu', 'Seimeni', 'Siliștea', 'Târgușor', 'Topraisar',
    'Tortoman', 'Tuzla', 'Valu lui Traian', 'Vulturu',
  ],
  'Covasna': [
    'Sfântu Gheorghe', 'Târgu Secuiesc', 'Covasna', 'Baraolt', 'Întorsura Buzăului',
    'Bixad', 'Bodoc', 'Borsec', 'Brăduț', 'Brețcu', 'Catalina', 'Cernat', 'Chichiș',
    'Dobârlău', 'Estelnic', 'Ghidfalău', 'Hăghig', 'Ilieni', 'Lemnia', 'Moacșa',
    'Micfalău', 'Ojdula', 'Ozun', 'Păpăuți', 'Reci', 'Sânzieni', 'Sita Buzăului',
    'Turia', 'Vâlcele', 'Vârghiș', 'Zăbala', 'Zagon',
  ],
  'Dâmbovița': [
    'Târgoviște', 'Moreni', 'Pucioasa', 'Găești', 'Titu',
    'Aninoasa', 'Baleni', 'Bezdead', 'Bilciurești', 'Braniștea', 'Brezoaele', 'Buciumeni',
    'Cândeștii de Jos', 'Ciocănești', 'Cobia', 'Comișani', 'Conțești', 'Cornățel',
    'Corbii Mari', 'Coțofenii din Față', 'Crângurile', 'Crevedia', 'Dărmănești', 'Doicești',
    'Dragodana', 'Drăghicești', 'Fieni', 'Gura Foii', 'Gura Ocniței', 'Gura Șuții',
    'Hulubești', 'I.L. Caragiale', 'Lucieni', 'Lunca', 'Malu cu Flori', 'Mătăsaru',
    'Mogoșani', 'Moțăieni', 'Niculești', 'Nucet', 'Petrești', 'Pietrari',
    'Potigrafu', 'Produlești', 'Răcari', 'Razvad', 'Runcu', 'Slobozia Moară',
    'Șotânga', 'Tătărani', 'Ulmi', 'Ulmeni', 'Valea Mare', 'Văcărești', 'Văcărești',
    'Vișina', 'Vișinești', 'Vlădeni', 'Voinești', 'Vulcana Băi', 'Vulcana Pandele',
  ],
  'Dolj': [
    'Craiova', 'Băilești', 'Calafat', 'Filiaș', 'Segarcea', 'Dăbuleni', 'Bechet',
    'Amărăștii de Jos', 'Amărăștii de Sus', 'Argetoaia', 'Basarabi', 'Botoșești-Paia',
    'Braloștița', 'Braniștea', 'Breasta', 'Bucovăț', 'Bulzești', 'Cârcea', 'Calopar',
    'Caraula', 'Cârna', 'Catane', 'Celaru', 'Cernele', 'Cerăt', 'Cosoveni', 'Coțofenii din Față',
    'Desa', 'Diosti', 'Dobrești', 'Dragotești', 'Drănic', 'Galicea Mare', 'Ghercești',
    'Gingiova', 'Giubega', 'Giurgița', 'Gogoșu', 'Goicea', 'Goiești', 'Grecești',
    'Ișalnița', 'Izvoare', 'Leu', 'Lipovu', 'Maceșu de Jos', 'Melinești', 'Moțăței',
    'Murgași', 'Ostroveni', 'Perișor', 'Piscu Vechi', 'Plenița', 'Pleșoi', 'Poiana Mare',
    'Predești', 'Radovan', 'Robănești', 'Rojiște', 'Sadova', 'Scăești', 'Seaca de Câmp',
    'Siliștea Crucii', 'Șimnicu de Sus', 'Teasc', 'Terpezița', 'Unirea', 'Urzicuța',
    'Valea Stanciului', 'Vârtop', 'Vela', 'Verbița', 'Vrata',
  ],
  'Galați': [
    'Galați', 'Tecuci', 'Târgu Bujor', 'Berești',
    'Bălășești', 'Băneasa', 'Barcea', 'Brăhășești', 'Braniștea', 'Buciumeni', 'Cavadinești',
    'Cerești', 'Costache Negri', 'Corod', 'Cosmești', 'Cudalbi', 'Cuza Vodă',
    'Drăgănești', 'Drăgușeni', 'Fârtănești', 'Filești', 'Frumușița', 'Fundeni',
    'Ghidigeni', 'Gohor', 'Griviță', 'Independența', 'Ivești', 'Jorăști',
    'Liești', 'Măstăcani', 'Movileni', 'Munteni', 'Nicorești', 'Oancea', 'Pechea',
    'Piscu', 'Priponești', 'Rediu', 'Rogojeni', 'Schela', 'Scânteiești', 'Sendreni',
    'Slobozia Conachi', 'Smârdani', 'Smulți', 'Suceveni', 'Șendreni', 'Tudor Vladimirescu',
    'Tulucești', 'Umbrărești', 'Ungureni', 'Valea Mărului', 'Vânători', 'Vlădești',
  ],
  'Giurgiu': [
    'Giurgiu', 'Bolintin-Vale', 'Mihăilești',
    'Băneasa', 'Bolintin-Deal', 'Bujoru', 'Bulbucata', 'Buturugeni', 'Călugăreni',
    'Clejani', 'Colibași', 'Comana', 'Cosoba', 'Daia', 'Florești-Stoenești',
    'Frăsinetu de Jos', 'Găiseni', 'Găujani', 'Ghimpați', 'Gogoșari', 'Gostinu',
    'Grădinari', 'Greaca', 'Herești', 'Hotarele', 'Iepurești', 'Isvoarele',
    'Izvoarele', 'Joița', 'Letca Nouă', 'Mărginenii de Jos', 'Mihai Bravu',
    'Mironești', 'Ogrezeni', 'Oinacu', 'Prundu', 'Putineiu', 'Radu Vodă',
    'Remuș', 'Roata de Jos', 'Schitu', 'Singureni', 'Slobozia', 'Stănoaia',
    'Stoenești', 'Toporu', 'Ulmi', 'Valea Dragului',
  ],
  'Gorj': [
    'Târgu Jiu', 'Motru', 'Rovinari', 'Bumbești-Jiu', 'Tismana', 'Novaci',
    'Baia de Fier', 'Bengești-Ciocadia', 'Bustuchin', 'Câlnic', 'Căpreni', 'Crasna',
    'Crușeț', 'Danești', 'Drăgotești', 'Drăguțești', 'Farcășești', 'Florești',
    'Godeni', 'Hurezani', 'Iași', 'Ionești', 'Jupânești', 'Lelești', 'Licurici',
    'Mătăsari', 'Mușetești', 'Negomir', 'Peștișani', 'Plopșoru', 'Polovragi',
    'Prigoria', 'Rânca', 'Roșia de Amaradia', 'Runcu', 'Samarinești', 'Scoarța',
    'Slivești', 'Stănești', 'Stejari', 'Stoina', 'Șimnicu de Jos', 'Turcinești',
    'Urdari', 'Văgiulești', 'Vladimir',
  ],
  'Harghita': [
    'Miercurea Ciuc', 'Odorheiu Secuiesc', 'Gheorgheni', 'Toplița', 'Băile Tușnad', 'Vlăhița',
    'Borsec', 'Cristuru Secuiesc', 'Bălan',
    'Atid', 'Avrămeștii', 'Bilbor', 'Borsec', 'Brădeștii de Sus', 'Cârța',
    'Ciumani', 'Ciumași', 'Corbu', 'Cozmeni', 'Dănești', 'Depuri', 'Dittró',
    'Ferenczi', 'Feliceni', 'Filiași', 'Frumoasa', 'Gălăuțaș', 'Ighiu',
    'Întorsura Buzăului', 'Joseni', 'Lăzarea', 'Lueta', 'Lunca de Jos', 'Lunca de Sus',
    'Lupeni', 'Mărtiniș', 'Mihăileni', 'Mugeni', 'Ocland', 'Praid', 'Racu',
    'Remetea', 'Satu Mare', 'Sândominic', 'Sânmartin', 'Sânsimion', 'Sântimbru',
    'Secuieni', 'Sf. Ana', 'Subcetate', 'Suseni', 'Șimoneștii', 'Tulgheș', 'Ulieș',
    'Vărșag', 'Voșlăbeni',
  ],
  'Hunedoara': [
    'Deva', 'Hunedoara', 'Brad', 'Orăștie', 'Petroșani', 'Lupeni', 'Vulcan', 'Simeria',
    'Uricani', 'Petrila', 'Aninoasa', 'Pui',
    'Băița', 'Baia de Criș', 'Balșa', 'Bănița', 'Baru', 'Bâtrina', 'Beriu',
    'Blăjeni', 'Boșorod', 'Brănișca', 'Bretea Română', 'Buces', 'Bulzești',
    'Bunila', 'Burjuc', 'Cârjiți', 'Cârpiniș', 'Cerbal', 'Certeju de Sus', 'Densus',
    'General Berthelot', 'Geoagiu', 'Hărău', 'Ilia', 'Lăpugiu de Jos', 'Lunca Cernii',
    'Luncoiu de Jos', 'Mărtinești', 'Micești', 'Pestișu Mic', 'Rîu de Mori',
    'Romos', 'Roșcani', 'Săcel', 'Salașu de Sus', 'Sarmizegetusa', 'Soimus',
    'Șoimuș', 'Tomeștii de Jos', 'Totești', 'Turdaș', 'Vălișoara', 'Vețel',
    'Zam', 'Densus',
  ],
  'Ialomița': [
    'Slobozia', 'Fetești', 'Urziceni', 'Amara', 'Căzănești',
    'Adâncata', 'Alexeni', 'Andrășești', 'Armășești', 'Axintele', 'Balaciu',
    'Bărbulești', 'Barcea', 'Bordușani', 'Borănești', 'Brazii', 'Bucu', 'Bulboaca',
    'Ciochina', 'Ciulnița', 'Cocora', 'Colelia', 'Coșereni', 'Cosâmbești',
    'Dridu', 'Dridu Snagov', 'Eftimie Murgu', 'Făcăeni', 'Fierbinți-Târg', 'Gheorghe Doja',
    'Gheorghe Lazăr', 'Giurgeni', 'Grivița', 'Gura Ialomiței', 'Gura Văii', 'Ion Roată',
    'Jilavele', 'Maia', 'Mândrești', 'Manasia', 'Mihail Kogălniceanu', 'Miloșești',
    'Moldoveni', 'Movilița', 'Munteni Buzău', 'Ograda', 'Perieți', 'Reviga',
    'Rași', 'Râszeri', 'Sălcioara', 'Sângeorgiu', 'Scânteia', 'Sfântu Gheorghe',
    'Slobozia', 'Ștefan cel Mare', 'Sudiți', 'Traian', 'Vlădeni', 'Zorile',
  ],
  'Iași': [
    'Iași', 'Pașcani', 'Hârlău', 'Târgu Frumos', 'Podu Iloaiei',
    'Andrieșeni', 'Aroneanu', 'Bălțați', 'Bârnova', 'Belcești', 'Bivolari',
    'Brăești', 'Butea', 'Cepleniță', 'Ciortești', 'Ciurea', 'Coarnele Caprei',
    'Cotnari', 'Costești', 'Costuleni', 'Cozmeștii', 'Cristești', 'Cucuteni',
    'Deleni', 'Dobrovăț', 'Dolhești', 'Drăguşeni', 'Dumeștiiii', 'Erbiceni',
    'Focuri', 'Frunzișoara', 'Gârcina', 'Golăiești', 'Gorban', 'Grajduri',
    'Helăuăști', 'Holboca', 'Horleștii de Jos', 'Ipatele', 'Lespezi', 'Lețcani',
    'Lungani', 'Mogoșești', 'Mogoșești-Siret', 'Movileni', 'Moșna', 'Mușata',
    'Oțeleni', 'Plugari', 'Popricani', 'Prisăcani', 'Probota', 'Răchiteni',
    'Răducăneni', 'Rediu', 'Romanești', 'Roșcani', 'Ruginoasa', 'Schitu Duca',
    'Scânteia', 'Sinești', 'Sipote', 'Șcheia', 'Scheia', 'Todirești', 'Tomești',
    'Trifești', 'Tudora', 'Țibănești', 'Ungheni', 'Vânători', 'Vlădeni',
    'Voineștii de Jos', 'Victoria', 'Zaboloteni',
  ],
  'Ilfov': [
    'Buftea', 'Voluntari', 'Popești-Leordeni', 'Pantelimon', 'Otopeni', 'Chitila',
    'Măgurele', 'Bragadiru', 'Tunari',
    'Afumați', 'Balotești', 'Berceni', 'Brănești', 'Cernica', 'Chiajna', 'Clinceni',
    'Copăceni', 'Cornetu', 'Ciorogârla', 'Dărăști-Ilfov', 'Dobroești', 'Domneștii de Jos',
    'Dragomirești-Vale', 'Gănești', 'Găvănești', 'Glina', 'Grădiștea', 'Gruiu', 'Jilava',
    'Joița', 'Mogoșoaia', 'Nuci', 'Petrăchioaia', 'Periș', 'Pereța', 'Poienarii Apostoli',
    '1 Decembrie', 'Roșu', 'Snagov', 'Ștubei', 'Vidra',
  ],
  'Maramureș': [
    'Baia Mare', 'Sighetu Marmației', 'Borșa', 'Vișeu de Sus', 'Târgu Lăpuș', 'Cavnic',
    'Seini', 'Tăuții-Măgherăuș',
    'Ardusat', 'Ariniș', 'Bârsana', 'Băiuț', 'Bicaz', 'Bistra', 'Bocicoiu Mare',
    'Bogdan Vodă', 'Botiza', 'Budești', 'Cernești', 'Cicârlău', 'Copalnic-Mănăștur',
    'Coroieni', 'Cupșeni', 'Desești', 'Farcașa', 'Giulești', 'Groșii Țibleșului',
    'Ieud', 'Lăpuș', 'Leordina', 'Moisei', 'Ocna Șugatag', 'Onești', 'Petrova',
    'Poienile de sub Munte', 'Poienile Izei', 'Remeci', 'Repedea', 'Remetea Chioarului',
    'Rona de Jos', 'Rona de Sus', 'Rozavlea', 'Ruscova', 'Săcălășeni', 'Sălsig',
    'Sângeorz-Băi', 'Sieu', 'Sisești', 'Strâmtura', 'Șieu', 'Șișești', 'Ulmeni',
    'Vadu Izei', 'Valea Chioarului', 'Vima Mică', 'Vișeu de Jos',
  ],
  'Mehedinți': [
    'Drobeta-Turnu Severin', 'Orșova', 'Strehaia', 'Vânju Mare', 'Baia de Aramă',
    'Balotești', 'Bâcleș', 'Bârveni', 'Breznița-Motru', 'Breznița-Ocol', 'Butoiești',
    'Căzănești', 'Cireșu', 'Corcova', 'Corlățel', 'Cujmir', 'Dârvari',
    'Devesel', 'Dubova', 'Florești', 'Gârla Mare', 'Godeanu', 'Gogoșu',
    'Greci', 'Gruia', 'Hinova', 'Husnicioara', 'Ilova', 'Ilovița', 'Iyvești',
    'Izvoru Bârzii', 'Jiana', 'Livezile', 'Malovăț', 'Ostrovu Mare',
    'Padina Mare', 'Patulele', 'Pătulele', 'Pristol', 'Punghina', 'Rogova',
    'Salcia', 'Șimian', 'Șișești', 'Vlădaia', 'Voloiac',
  ],
  'Mureș': [
    'Târgu Mureș', 'Sighișoara', 'Reghin', 'Târnăveni', 'Luduș', 'Sovata', 'Iernut',
    'Ungheni',
    'Acățari', 'Adămuș', 'Albești', 'Aluniș', 'Apold', 'Atintiș', 'Bălăușeri',
    'Bahnea', 'Band', 'Bichiș', 'Bogata', 'Breaza', 'Brâncovenești', 'Ceuașu de Câmpie',
    'Chețani', 'Chibed', 'Chiheru de Jos', 'Cozma', 'Crăciunești', 'Cristești', 'Cucerdea',
    'Curechi', 'Cuci', 'Daneș', 'Deda', 'Eremitu', 'Ernei', 'Fâncel', 'Fărăgău',
    'Găiești', 'Ghindari', 'Glodeni', 'Gorneștii', 'Grebenișu de Câmpie', 'Gurghiu',
    'Hodac', 'Hodosa', 'Ibănești', 'Iclanzel', 'Iclănzel', 'Miercurea Nirajului',
    'Miheșu de Câmpie', 'Nadeș', 'Neaua', 'Ogra', 'Pădureni', 'Papiu Ilarian',
    'Pasărea', 'Petelea', 'Pogăceaua', 'Răstolița', 'Ruși de Jos', 'Rușii Munți',
    'Sângeorgiu de Mureș', 'Sângeorgiu de Pădure', 'Sânger', 'Sânpetru de Câmpie',
    'Sânsimion', 'Sântana de Mureș', 'Sântioana de Mureș', 'Sânvăsii', 'Saschiz',
    'Sărmaș', 'Sincai', 'Stânceni', 'Șincai', 'Șincai Fâncel', 'Șărmășel', 'Tăureni',
    'Urmeniș', 'Vânători', 'Vătava', 'Veța', 'Viișoara', 'Voivodeni', 'Zagar',
  ],
  'Neamț': [
    'Piatra Neamț', 'Roman', 'Târgu Neamț', 'Bicaz', 'Roznov',
    'Agapia', 'Alexandru cel Bun', 'Bahna', 'Bara', 'Bâra', 'Bicaz-Chei', 'Bicazu Ardelean',
    'Bira', 'Bodeștii de Jos', 'Boghicea', 'Borleștii de Sus', 'Bozieni', 'Brusturi',
    'Ceahlău', 'Cordun', 'Costișa', 'Crăcăoani', 'Dobreni', 'Dochia', 'Doljești',
    'Dragomirești', 'Dulcești', 'Dumbrava Roșie', 'Farcașa', 'Gâdinți', 'Ghindăoani',
    'Girov', 'Grințieș', 'Hănțești', 'Horia', 'Icușești', 'Ion Creangă',
    'Mărgineni', 'Moldoveni', 'Negrești', 'Neamț', 'Oniceni', 'Petricani',
    'Piatra Șoimului', 'Poiana Teiului', 'Poienari', 'Rediu', 'Români', 'Ruginoasa',
    'Roznov', 'Sagna', 'Săvinești', 'Secuieni', 'Stâncești', 'Tarcău', 'Timișești',
    'Trifești', 'Tupilatii', 'Urecheni', 'Valea Ursului', 'Vânători Neamț',
  ],
  'Olt': [
    'Slatina', 'Caracal', 'Balș', 'Corabia', 'Drăgănești-Olt', 'Scornicești',
    'Piatra Olt', 'Potcoava',
    'Băbiciu', 'Baldovinești', 'Barza', 'Bâlteni', 'Bărăști', 'Brebeni', 'Brâncoveni',
    'Buta', 'Câțulești', 'Calui', 'Cezieni', 'Cilieni', 'Colonești', 'Corbu',
    'Coteana', 'Crâmpoia', 'Crișan', 'Curtișoara', 'Dăești', 'Dănesci', 'Deveselu',
    'Dobrești', 'Dobrun', 'Drăghiceni', 'Fâlcoiu', 'Față', 'Floru',
    'Gârcov', 'Găneasa', 'Ghimpețeni', 'Giuvărăști', 'Grădinile', 'Greci',
    'Ipotești', 'Ianca', 'Iancu Jianu', 'Izbiceni', 'Leleasca', 'Luci',
    'Lunca', 'Mârsani', 'Morunglav', 'Movileni', 'Nicolae Titulescu',
    'Oporelu', 'Optași-Măgura', 'Orlea', 'Osica de Jos', 'Osica de Sus',
    'Perieți', 'Pleșoiu', 'Poboru', 'Priseaca', 'Radomirești', 'Redea',
    'Rotunda', 'Rusănești', 'Schitu', 'Scorniceşti', 'Seaca', 'Spineni',
    'Stoicănești', 'Stoicea', 'Studina', 'Sâmbureștii de Sus', 'Tătulești',
    'Topana', 'Traian', 'Tufeni', 'Urzica', 'Vâlcele', 'Verguleasa',
    'Vitomirești', 'Vlădila', 'Voineasa',
  ],
  'Prahova': [
    'Ploiești', 'Câmpina', 'Sinaia', 'Bușteni', 'Azuga', 'Mizil', 'Urlați', 'Băicoi',
    'Vălenii de Munte', 'Boldești-Scăeni', 'Breaza', 'Comarnic',
    'Adunați', 'Albești-Paleologu', 'Aluniș', 'Apostolache', 'Ariceștii Rahtivani',
    'Ariceștii Zeletin', 'Baba Ana', 'Balta Doamnei', 'Bănești', 'Bărcănești',
    'Berceni', 'Bertea', 'Blejoi', 'Bobolia', 'Bodo', 'Bogdănești',
    'Brazi', 'Bucov', 'Câmpina', 'Cerașu', 'Cheia', 'Chiojdeanca', 'Ciorani',
    'Cocorăști Colt', 'Cocorăști Mislii', 'Colceag', 'Corlătești', 'Doftana',
    'Drăgănești', 'Drăgănești-Prahova', 'Dumbrava', 'Dumbrăvești', 'Filipeștii de Pădure',
    'Florești', 'Fulga', 'Gorgota', 'Gornet', 'Gornet Cricov', 'Gura Vadului',
    'Gura Vitioarei', 'Iordăcheanu', 'Jugureni', 'Lipănești', 'Luncavița',
    'Măgurele', 'Maneciu', 'Olari', 'Pâclele', 'Plopu',
    'Posești', 'Predeal-Sărari', 'Provița de Jos', 'Provița de Sus', 'Puchenii Mari',
    'Râfov', 'Salcia', 'Secăria', 'Scăeni', 'Șoimari', 'Șotrile',
    'Talea', 'Tătărani', 'Telega', 'Tomșani', 'Vărbilău',
  ],
  'Satu Mare': [
    'Satu Mare', 'Carei', 'Negrești-Oaș', 'Tășnad', 'Ardud',
    'Acâș', 'Agriș', 'Andrid', 'Apa', 'Batăr', 'Beltiug', 'Berveni', 'Bixad',
    'Bogdand', 'Botiz', 'Călinești-Oaș', 'Cămărzana', 'Cămin', 'Capleni',
    'Certeze', 'Chelinți', 'Dorolț', 'Foieni', 'Gelu', 'Ghenci', 'Hodod',
    'Homoroade', 'Lazuri', 'Livada', 'Medieșu Aurit', 'Micula', 'Moftin',
    'Moișeni', 'Odoreu', 'Orașu Nou', 'Orosfaia', 'Pelișor', 'Pișcari',
    'Pișcolt', 'Pomi', 'Racșa', 'Remetea Oașului', 'Săcășeni', 'Satu Mic',
    'Socond', 'Supur', 'Tiream', 'Turț', 'Urziceni', 'Valea Vinului', 'Vetis', 'Viile Satu Mare',
  ],
  'Sălaj': [
    'Zalău', 'Șimleu Silvaniei', 'Cehu Silvaniei', 'Jibou',
    'Agrij', 'Almașu', 'Băbeni', 'Bălan', 'Bobota', 'Bocșa', 'Boghiș',
    'Camăr', 'Chieșd', 'Ciucea', 'Cizer', 'Coșeiu', 'Crasna', 'Crișeni',
    'Dobrin', 'Dragu', 'Fildu de Jos', 'Gâlgău', 'Gârbou', 'Horoatu Crasnei',
    'Hida', 'Ileanda', 'Letca', 'Lozna', 'Marca', 'Meseșenii de Jos',
    'Mirșid', 'Nușfalău', 'Pericei', 'Plopiș', 'Poiana Blenchii', 'Românaș',
    'Rus', 'Sânmihaiu Almașului', 'Someș-Odorhei', 'Surduc', 'Șamșud',
    'Șărmășag', 'Treznea', 'Turd', 'Valcău de Jos', 'Vârșolț', 'Zalha',
  ],
  'Sibiu': [
    'Sibiu', 'Mediaș', 'Cisnădie', 'Miercurea Sibiului', 'Avrig', 'Agnita', 'Copșa Mică',
    'Ocna Sibiului', 'Dumbrăveni', 'Tălmaciu',
    'Alțina', 'Apold', 'Arpașu de Jos', 'Axente Sever', 'Bârghiș', 'Biertan',
    'Blăjel', 'Boian', 'Brădeni', 'Bruiu', 'Chirpăr', 'Coveș', 'Cristian',
    'Deal', 'Dobârca', 'Dupuș', 'Gura Râului', 'Hoghilag', 'Iacobeni', 'Jina',
    'Laslea', 'Loamneș', 'Ludoș', 'Marpod', 'Merghindeal', 'Mihăileni', 'Moșna',
    'Netedu', 'Nocrich', 'Orlat', 'Păuca', 'Poplaca', 'Porumbacu de Jos',
    'Racovița', 'Râu Sadului', 'Rășinari', 'Rod', 'Roșia', 'Sadu', 'Sălișteа',
    'Seica Mare', 'Seica Mică', 'Slimnic', 'Șura Mare', 'Șura Mică',
    'Tilișca', 'Torre Blanca', 'Turnu Roșu', 'Vurpăr', 'Vălchid',
  ],
  'Suceava': [
    'Suceava', 'Rădăuți', 'Fălticeni', 'Câmpulung Moldovenesc', 'Vatra Dornei', 'Gura Humorului',
    'Siret', 'Vicovu de Sus', 'Liteni',
    'Adâncata', 'Arbore', 'Baia', 'Bălcăuți', 'Berchișești', 'Bilca', 'Bogdănești',
    'Boroaia', 'Bosanci', 'Broșteni', 'Bunești', 'Cacica', 'Cajvana', 'Calafindești',
    'Câmpulung Moldovenesc', 'Capu Câmpului', 'Ciprian Porumbescu', 'Ciumârna', 'Comănești',
    'Cornu Luncii', 'Coșna', 'Costâna', 'Costișa', 'Crucea', 'Dorna Arini', 'Dorna-Candreni',
    'Dornești', 'Drăgoiești', 'Dumbrava', 'Fântânele', 'Forăști', 'Frasin', 'Frătăuții Noi',
    'Frătăuții Vechi', 'Fundu Moldovei', 'Grănicești', 'Iaslovăț', 'Iacobeni', 'Ilișești',
    'Ipotești', 'Izvoarele Sucevei', 'Mălini', 'Mănăstirea Humorului', 'Mitocu Dragomirnei',
    'Moara', 'Moldova-Sulița', 'Moldovița', 'Mudsatia', 'Ostra', 'Părhăuți', 'Panaci',
    'Poiana Stampei', 'Pojorâta', 'Preutești', 'Putna', 'Răchitna', 'Rădășeni',
    'Râșca', 'Salcea', 'Satu Mare', 'Scheia', 'Slatina', 'Stroiești', 'Stulpicani',
    'Sucevița', 'Șcheia', 'Tereblecea', 'Todirești', 'Udeștii', 'Ulma', 'Vadu Moldovei',
    'Vama', 'Vatra Moldoviței', 'Verești', 'Vicovu de Jos', 'Voitinel', 'Volovat',
    'Vulturești', 'Zamostea', 'Zvoriștea',
  ],
  'Teleorman': [
    'Alexandria', 'Roșiorii de Vede', 'Turnu Măgurele', 'Zimnicea', 'Videle',
    'Balaci', 'Bălăci', 'Beuca', 'Blejești', 'Bogdana', 'Branceni', 'Brânzeni',
    'Bujoreni', 'Bujoru', 'Buzescu', 'Călinești', 'Cervenia', 'Ciolănești',
    'Ciuperceni', 'Conțești', 'Cosești', 'Crângeni', 'Crângu', 'Crevenicu',
    'Didești', 'Dracșenei', 'Drăcșenei', 'Drăgănești de Vede', 'Drăgănești-Vlașca',
    'Furculeștii', 'Gălătenii', 'Gratia', 'Groși', 'Islaz', 'Izvoarele',
    'Lița', 'Livia', 'Lunca', 'Lupșanu', 'Mâgurele', 'Mârzănești', 'Merenii de Jos',
    'Moșteni', 'Nanov', 'Năsturelu', 'Nenciulești', 'Olteni', 'Piatra', 'Pitaru',
    'Plopii-Slăvitești', 'Poeni', 'Poroschia', 'Purani', 'Putineiu', 'Rădoiești',
    'Rășești', 'Salcia', 'Saelele', 'Scrioaștea', 'Seaca', 'Segarcea Vale', 'Sfințești',
    'Siliștea', 'Slobozia Mândra', 'Smârdioasa', 'Stejarii', 'Storobăneasa',
    'Suhaia', 'Talpa', 'Tătărăsitii de Jos', 'Tecuci', 'Teleormanu', 'Tiganesti',
    'Traian', 'Trivalea Mosteni', 'Trufinești', 'Uda-Clocociov', 'Văcărești',
    'Vedea', 'Vânătorii Mici', 'Viișoara', 'Vitănești', 'Vlăsceni', 'Vrânești',
    'Zâmbreasca', 'Zimnicea',
  ],
  'Timiș': [
    'Timișoara', 'Lugoj', 'Sânnicolau Mare', 'Jimbolia', 'Deta', 'Buziaș', 'Recaș', 'Făget',
    'Ciacova',
    'Banloc', 'Bara', 'Barna', 'Becicherecu Mic', 'Belinț', 'Biled', 'Birda',
    'Bogda', 'Boldur', 'Brestovăț', 'Bucovăț', 'Buziașu', 'Carpiniș', 'Cenad',
    'Cenei', 'Checea', 'Chevereșu Mare', 'Comloșu Mare', 'Coșteiu', 'Criciova',
    'Curtea', 'Darova', 'Denta', 'Dudeștii Noi', 'Dudeștii Vechi', 'Fibiș',
    'Foeni', 'Gad', 'Gavojdia', 'Ghiroda', 'Giarmata', 'Giera', 'Giroc',
    'Giulvăz', 'Gottlob', 'Iecea Mare', 'Jebel', 'Lenauheim', 'Liebling',
    'Livezile', 'Lovrin', 'Masloc', 'Mașloc', 'Moșnița Nouă', 'Moșnița Veche',
    'Nădrag', 'Niță Mangu', 'Orțișoara', 'Otelec', 'Pădureni', 'Parța', 'Periam',
    'Peciu Nou', 'Pesac', 'Pietroasa', 'Pischia', 'Pișchia', 'Remetea Mare',
    'Sacoșu Turcesc', 'Satchinez', 'Sânandrei', 'Sânmihaiu Român', 'Sânpetru Mare',
    'Seca', 'Secaș', 'Şag', 'Şandra', 'Șanovița', 'Topolovățu Mare', 'Tomnatic',
    'Uivar', 'Unip', 'Utvin', 'Victor Vlad Delamarina', 'Voiteg',
  ],
  'Tulcea': [
    'Tulcea', 'Sulina', 'Babadag', 'Măcin', 'Isaccea',
    'Baia', 'Beștepe', 'C.A. Rosetti', 'Casimcea', 'Ceamurlia de Jos', 'Ceatalchioi',
    'Chilia Veche', 'Ciucurova', 'Cișmeaua Nouă', 'Crișan', 'Dăeni', 'Dobra',
    'Frecăței', 'Greci', 'Grindu', 'Horia', 'I.C. Brătianu', 'Ilganii de Sus',
    'Jurilovca', 'Luncavița', 'Mahmudia', 'Maliuc', 'Mihai Bravu', 'Mihail Kogălniceanu',
    'Murighiol', 'Nalbant', 'Niculițel', 'Nufăru', 'Ostrov', 'Pardina',
    'Peceneaga', 'Sarichioi', 'Sfântu Gheorghe', 'Slava Cercheză', 'Smârdan',
    'Somova', 'Stejaru', 'Topolog', 'Turcoaia', 'Văcăreni', 'Valea Nucarilor',
    'Victoria',
  ],
  'Vaslui': [
    'Vaslui', 'Bârlad', 'Huși', 'Negrești',
    'Alexandru Vlahuță', 'Băcani', 'Banca', 'Berezeni', 'Blăgeștii', 'Bogdănița',
    'Bogdănești', 'Borolea', 'Bunești-Averești', 'Ceplenița', 'Ciocani', 'Codăești',
    'Costești', 'Cozmești', 'Crețești', 'Dăneți', 'Deleștii', 'Deleni',
    'Dimitrie Cantemir', 'Dobârlău', 'Dragomirești', 'Drânceni', 'Dumești',
    'Epureni', 'Fălciu', 'Ferești', 'Fruntișeni', 'Fundătura', 'Gâgești',
    'Ghermanești', 'Griviță', 'Hoceni', 'Iana', 'Ivanesti', 'Ivăneștii de Jos',
    'Laza', 'Lipovăț', 'Lunca Banului', 'Mălușteni', 'Mihăileni', 'Miclești',
    'Muntenii de Jos', 'Muntenii de Sus', 'Oșești', 'Pădureni', 'Perieni',
    'Pochidia', 'Poienești', 'Poienesti', 'Pungești', 'Puiești', 'Rădești',
    'Roșiești', 'Roșieni', 'Ruginoasa', 'Schitu Duca', 'Ștefan cel Mare', 'Tanacu',
    'Tătărăni', 'Todirești', 'Tutova', 'Unțeni', 'Văleni', 'Vânători',
    'Vinderei', 'Viișoara', 'Zorleni',
  ],
  'Vâlcea': [
    'Râmnicu Vâlcea', 'Drăgășani', 'Brezoi', 'Băile Govora', 'Băile Olănești',
    'Ocnele Mari', 'Horezu', 'Băbeni', 'Balcești', 'Berbești', 'Călimănești',
    'Bălcești', 'Amărăștii de Sus',
    'Alunu', 'Bârsești', 'Berislavești', 'Berislăvești', 'Boișoara', 'Brădetu',
    'Budești', 'Bukoveni', 'Bunești', 'Câinenii Mari', 'Căzănești', 'Cernavodă',
    'Copăceni', 'Costești', 'Creți', 'Cremenari', 'Crocmaz', 'Dăești', 'Diculești',
    'Dobriceni', 'Drăgoești', 'Fârtățești', 'Florești', 'Frâncești', 'Găujani',
    'Ghioroiu', 'Goranu', 'Grădiștea', 'Gruiu', 'Gușoieni', 'Iibănești', 'Ionești',
    'Lăcusteni', 'Lăpușata', 'Lăpușnicu Mare', 'Lungești', 'Măciuca', 'Mădulari',
    'Mihăești', 'Milcoiu', 'Mitrofani', 'Muereasca', 'Negrulești', 'Nicolae Bălcescu',
    'Olanu', 'Oteșani', 'Păușești', 'Păușești-Măglași', 'Perișani', 'Pietrari',
    'Popești', 'Prundeni', 'Racovița', 'Roești', 'Runcu', 'Săcelu', 'Scundu',
    'Sinești', 'Slătioara', 'Stănești', 'Stoilești', 'Stroești', 'Susani',
    'Șirineasa', 'Titești', 'Tomsani', 'Vaideeni', 'Valea Mare', 'Vlădești',
    'Voicești', 'Voineasa', 'Vulpeni', 'Zătreni',
  ],
  'Vrancea': [
    'Focșani', 'Adjud', 'Mărășești', 'Panciu', 'Odobești',
    'Andreiaşu de Jos', 'Bârseștii de Jos', 'Bolotești', 'Bonțești', 'Bordeasca',
    'Broșteni', 'Câmpineanca', 'Câmpuri', 'Ciorăști', 'Ciorani', 'Corbița',
    'Cotești', 'Dumbrava', 'Dumești', 'Dumitrești', 'Fitionești', 'Garoafa',
    'Golești', 'Gugeşti', 'Gugești', 'Homocea', 'Jaristea', 'Jitia', 'Milcovul',
    'Movilița', 'Năruja', 'Nereju', 'Nereju Mic', 'Nișipuri', 'Obrejița',
    'Paltin', 'Paulești', 'Ploscuțeni', 'Poiana Cristei', 'Popești',
    'Pufești', 'Răcoasa', 'Reghiu', 'Rugineasa', 'Rugineasca', 'Sihlea',
    'Slobozia Bradului', 'Slobozia Ciorăști', 'Soveja', 'Suraia', 'Șindrilari',
    'Tâmboești', 'Tătăranu', 'Tulnici', 'Urechești', 'Vâlcele', 'Vârteșcoiu',
    'Vidra', 'Vintileasca', 'Vizantea Livezi', 'Vrâncioaia', 'Vulturu',
  ],
};
